apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ./deployment-environment-variables.yaml
- ./deployment-volumes.yaml
- ./deployment-server-port.yaml
- ./deployment-sa.yaml
images:
- name: nginx
  newTag: latest
resources:
- ../base
