apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: data-product-delivery
  namespace: vehicle-lifecycle
resources:
- ./deployment.yaml
- ./service.yaml
- ./hpa.yaml
- ./sa.yaml
