apiVersion: batch/v1
kind: Job
metadata:
  name: myapp12
  namespace: myapp
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: kustomize-and-conftest
          image: praveen888/opa:v4
          command: ["/bin/sh", "-c"]
          args: ["git clone https://github.com/devops-praveen/argocd-applications.git  && kubectl kustomize argocd-applications/dev > argocd-applications/dev/raw.yaml && conftest test -p test.rego argocd-applications/dev/raw.yaml"]
          env:
            - name: GIT_TERMINAL_PROMPT
              value: "0"  # To avoid interactive prompts during git clone
      restartPolicy: Never
  backoffLimit: 0